// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-d8bze5VQmb8IIiEzpLxkXoB0EzgZtFQ',
    appId: '1:512293553705:web:f82e6397981bb7c82c7e38',
    messagingSenderId: '512293553705',
    projectId: 'doctor-app-da559',
    authDomain: 'doctor-app-da559.firebaseapp.com',
    storageBucket: 'doctor-app-da559.appspot.com',
    measurementId: 'G-L3V67TS17J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-LMEGR2wfEByuLoCj6JlYa_AV1U0zvKI',
    appId: '1:512293553705:android:de1c6dd0a23f98982c7e38',
    messagingSenderId: '512293553705',
    projectId: 'doctor-app-da559',
    storageBucket: 'doctor-app-da559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-_LzU71irhwGeoWcPQCMiVIy9vfHBKcg',
    appId: '1:512293553705:ios:e46f116936a5cf652c7e38',
    messagingSenderId: '512293553705',
    projectId: 'doctor-app-da559',
    storageBucket: 'doctor-app-da559.appspot.com',
    iosClientId: '512293553705-7ovous3phh0p36hshntt8qqieknhe0am.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-_LzU71irhwGeoWcPQCMiVIy9vfHBKcg',
    appId: '1:512293553705:ios:59cd564d96d58d9d2c7e38',
    messagingSenderId: '512293553705',
    projectId: 'doctor-app-da559',
    storageBucket: 'doctor-app-da559.appspot.com',
    iosClientId: '512293553705-me7h7pj8mgaagj4omk7c8sqqm0s3i7mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorsApp.RunnerTests',
  );
}
